geo: "Israel"
titles:
  # DevOps Leadership
  - "Head of DevOps"
  - "DevOps Group Lead"
  - "Director of DevOps" 
  - "DevOps Director"
  - "DevOps Manager"
  - "VP DevOps"
  - "VP of DevOps"
  - "Chief DevOps Officer"
  - "Chief DevOps"
  
  # Platform Engineering Leadership
  - "Head of Platform"
  - "Head of Platform Engineering"
  - "Platform Director" 
  - "Director of Platform"
  - "Director of Platform Engineering"
  - "Platform Manager"
  - "VP Platform"
  - "VP of Platform Engineering"
  
  # Infrastructure Leadership
  - "Head of Infrastructure"
  - "Infrastructure Director"
  - "Director of Infrastructure"
  - "Infrastructure Manager"
  - "VP Infrastructure"
  - "VP of Infrastructure"
  - "Chief Infrastructure Officer"
  
  # SRE Leadership
  - "Head of SRE"
  - "Head of Site Reliability"
  - "SRE Director"
  - "Director of SRE"
  - "Director of Site Reliability"
  - "SRE Manager"
  - "VP SRE"
  - "VP of Site Reliability"
  
  # Engineering Operations & Production
  - "Head of Engineering Operations"
  - "Director of Engineering Operations"
  - "VP Engineering Operations"
  - "Head of Production Engineering"
  - "Director of Production Engineering"
  - "Production Owner"
  - "Head of Production"
  
  # Cloud & Architecture Leadership
  - "Head of Cloud"
  - "Cloud Director"
  - "Director of Cloud"
  - "VP Cloud"
  - "VP of Cloud Engineering"
  - "Head of Cloud Engineering"
  - "Solutions Architect Director"
  - "Principal Solutions Architect"
  
  # Technology Leadership (Senior)
  - "VP Engineering"
  - "VP of Engineering"
  - "Director of Engineering"
  - "Engineering Manager" 
  - "Senior Engineering Manager"
  - "Principal Engineering Manager"
  - "CTO"
  - "Chief Technology Officer"
  - "VP Technology"
  - "VP of Technology"
  
  # Security Engineering Leadership
  - "Head of Security Engineering"
  - "Director of Security Engineering"
  - "VP Security Engineering"
  - "CISO" 
  - "Chief Information Security Officer"
sources:
  greenhouse:
    companies:
      # Working Israeli Tech Companies
      - riskified           # E-commerce fraud prevention - WORKS
      - jfrog               # DevOps and MLOps platform - WORKS
      - taboola             # Content discovery platform - WORKS
      - nice                # Customer experience solutions - WORKS
      - via                 # Transit technology - WORKS
      - payoneer            # Global payment platform - WORKS
      - pagaya              # AI-driven financial services - WORKS
      
      # Additional Israeli Companies to Test
      - monday              # Work OS platform - Test if uses Greenhouse
      - wix                 # Website builder - Test if uses Greenhouse
      - fiverr              # Freelance marketplace - Test if uses Greenhouse
      - gong                # Revenue intelligence - Test if uses Greenhouse
      - outbrain            # Content discovery - Test if uses Greenhouse
      - checkmarx           # Application security - Test if uses Greenhouse
      - cyberark            # Privileged access - Test if uses Greenhouse
      - walkme              # Digital adoption - Test if uses Greenhouse
      
      # Working Global Companies with Israeli Offices  
      - snyk                # Developer security platform - WORKS
      - redis               # In-memory database - WORKS
      - elastic             # Search and analytics - WORKS
      - datadog             # Monitoring and security - WORKS
      - zscaler             # Cloud security platform - WORKS
      - solarwinds          # Infrastructure company - WORKS
      - mongodb             # Database company - WORKS
      - okta                # Identity management - WORKS
      - dropbox             # Cloud storage - WORKS
      - nvidia              # AI/GPU company - Test if uses Greenhouse
      - microsoft           # Cloud/software - Test if uses Greenhouse
      - google              # Search/cloud - Test if uses Greenhouse
  lever:
    companies:
      - spotify             # Spotify - Has Israeli R&D - WORKS
  company_pages: []         # add direct JSON/RSS endpoints if you have
  
  # Additional Israeli job sources
  israeli_sources:
    rss_feeds:
      - url: "https://www.themarker.com/career/rss/"
        name: "TheMarker Careers"
        type: "rss"
      - url: "https://www.alljobs.co.il/rss/jobs.aspx?region=2,3,4&category=2"
        name: "AllJobs Tech Central Israel"
        type: "rss"
    
    apis:
      comeet:
        companies: ["monday", "wix", "outbrain", "gong", "cyberark", "checkmarx", "riskified", "walkme", "fiverr", "ironSource", "nice", "lightricks"]
      smartrecruiters:
        companies: ["wix", "outbrain", "monday", "gong", "cyberark"]
        
    # Top Israeli Companies Career Pages
    career_pages:
      - url: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite"
        company: "nvidia-israel"
        type: "workday"
      - url: "https://careers.google.com/locations/israel/"
        company: "google-israel"
        type: "json"
      - url: "https://careers.microsoft.com/professionals/us/en/l-israel"
        company: "microsoft-israel"
        type: "html"
      - url: "https://jobs.sap.com/search/?q=&locationsearch=israel"
        company: "sap-israel"
        type: "html"
      
    vc_portfolios:
      bessemer: ["monday", "wix", "fiverr", "lightricks"]
      insight: ["armis", "orca-security", "snyk"] 
      viola: ["ironSource", "outbrain", "riskified"]
      83north: ["gong", "lemonade", "fundguard"]