name: Daily Job Search Pipeline

on:
  schedule:
    # Run daily at 05:30 UTC (≈ 08:30 Israel time)
    - cron: '30 5 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  job-search:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directories
      run: |
        mkdir -p data/raw data/processed outputs
        
    - name: Run crawl
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scripts/crawl.py
      
    - name: Run scoring
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scripts/score.py
      
    - name: Send Telegram digest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SCORE_THRESHOLD: ${{ vars.SCORE_THRESHOLD || '0.78' }}
        DIGEST_MAX: ${{ vars.DIGEST_MAX || '10' }}
      run: python scripts/digest.py
      
    - name: Push to Notion (optional)
      if: ${{ secrets.NOTION_API_KEY && secrets.NOTION_DB_ID }}
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      run: python scripts/notion_writer.py
      continue-on-error: true
      
    - name: Upload job data as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: job-search-data-${{ github.run_number }}
        path: |
          data/
          outputs/
        retention-days: 30
