name: Job Search Daily Digest

on:
  schedule:
    # 05:30 UTC ≈ 08:30 Asia/Jerusalem
    - cron: '30 5 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: jobsearch-pipeline-daily
  cancel-in-progress: true

jobs:
  digest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      SCORE_THRESHOLD: '0.78'
      DIGEST_MAX: '10'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl jobs
        run: |
          source .venv/bin/activate
          python scripts/crawl.py

      - name: Score matches
        run: |
          source .venv/bin/activate
          python scripts/score.py

      - name: Send Telegram digest
        run: |
          source .venv/bin/activate
          python scripts/digest.py

      - name: Optional Notion sync
        if: ${{ env.NOTION_API_KEY != '' && env.NOTION_DB_ID != '' }}
        run: |
          source .venv/bin/activate
          python scripts/notion_writer.py

      - name: Upload scores artifact
        uses: actions/upload-artifact@v4
        with:
          name: scores-jsonl
          path: outputs/scores.jsonl
          if-no-files-found: ignore
