name: Generate Cover Letter

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID to generate cover letter for'
        required: true
        type: string

jobs:
  tailor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        
    - name: Generate cover letter
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        python scripts/tailor.py ${{ github.event.inputs.job_id }}
        
    - name: Upload cover letter
      uses: actions/upload-artifact@v4
      with:
        name: cover-letter
        path: outputs/cover_letter.txt
        if-no-files-found: error
